name: Java master with Gradle
##자동 배포 서버 오류 재시작
on:
  push:
    branches: 
      - master

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/gradle_test.yml
    secrets:
      APPLICATION_PROPERTIES_TEST: ${{ secrets.APPLICATION_PROPERTIES_TEST }}
  
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      
          
        ## 1) git ignore에 등록된 application.properties 파일 생성해주기
      - name: make ENV
        run: |
          cd ./src/main/resources
          touch ./application.properties
          echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./application.properties
        shell: bash
          
        ## 2) 스프링 프로젝트 jar 파일 빌드
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build -x test

        ## 3) Docker Hub에 이미지 push 하기
            ## 웹 이미지 빌드 및 도커허브에 push
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: web docker build and push
        run: |
          docker build -t rolety2202/lottosimulator .
          docker push rolety2202/lottosimulator
        ## 4) Docker Hub에 Push한 이미지를 리눅스 서버에 받아와서 run
        
        
  deploy-dev:
    name: Deploy-dev
    needs: build
    runs-on: ubuntu-latest
    steps:     
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST_ADDRESS }}
          username: root
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 40022
          envs: GITHUB_SHA
          script: |
            cd docker
            docker pull rolety2202/lottosimulator:latest
            docker-compose up -d lottoSimulator-dev
  
  deploy-pro:
    name: Deploy-pro
    needs: deploy-dev
    runs-on: ubuntu-latest
    steps:     
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST_ADDRESS }}
          username: root
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 40022
          envs: GITHUB_SHA
          script: |
            cd docker
            docker pull rolety2202/lottosimulator:latest
            docker-compose up -d lottoSimulator

