name: Gradle test 

on:
  push:
    branches:  [ "master" ]
  workflow_call:
    secrets:
      APPLICATION_PROPERTIES_TEST:
        required: true
        
jobs:
  biuld:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: make ENV_test
        run: |
          cd ./src/test/resources
          touch ./application.properties
          echo "${{ secrets.APPLICATION_PROPERTIES_TEST }}" > ./application.properties
        shell: bash    
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew        
        
      - name: Test with Gradle
        run: ./gradlew --info test        
